### ISSUE TITLE
Latest Update - 8/18/16

### ISSUE THREAD

**Issue by Crumdidlyumshis** [ElvUI/ElvUI_FriendsListColor#2]
https://github.com/ElvUI/ElvUI_FriendsListColor/commit/c92fabf5c9f3ca59f2bc444bdcb0b57fba03de48

![world of warcraft 8_18_2016 2_47_37 pm](https://cloud.githubusercontent.com/assets/7307335/17788362/e6676336-6552-11e6-9e26-f49e55745704.png)

Shouldn't it be like this?:

Good:
Monka, Level 50 Hunter

Bad:
Monka,Level 50

Also, aren't the colors of the numbers (1-80) supposed to be colored in relation to your level?

**Comment by Bunny67** [comment]
Lua errors included?

**Comment by Crumdidlyumshis** [comment]
Hmm, ill try again. I didn't see any LUA errors popup.

**Comment by Crumdidlyumshis** [comment]
Nope, no LUA errors. I have it enabled.

**Comment by Bunny67** [comment]
new update removes the color level, is working only on the client ru :(

**Comment by Crumdidlyumshis** [comment]
Could the plugin have an option in ElvUI to enable color if preferred?

Maybe a Checkbox with yes or no color.

If not, which line could I edit to show the color?

**Comment by Bunny67** [comment]
check update

**Comment by Crumdidlyumshis** [comment]
Haha so close!

![world of warcraft 8_18_2016 3_28_39 pm](https://cloud.githubusercontent.com/assets/7307335/17789641/bae36c86-6558-11e6-876e-1d248c8bf1b7.png)

Almost there!

**Comment by Bunny67** [comment]
:(

**Comment by Bunny67** [comment]
check

**Comment by Crumdidlyumshis** [comment]
Ill mess with it and see if I can't help some. Your work is much appreciated Bunny!

**Comment by Crumdidlyumshis** [comment]
local textFormat = locale == "ruRU" and "%s%s|r, %s%s-го уровня" or locale == "enUS" and "%s%s|r, %sStufe %s" or "%s%s|r, %sLevel $s";

enUS

**Comment by Bunny67** [comment]
"%s%s|r, %sLevel $s" = all locale except the ruRU and deDE. 
not necessarily add enUS
Right now it works?

**Comment by Crumdidlyumshis** [comment]
I think I fixed it...  http://pastebin.com/vs0hanuZ

![world of warcraft 8_18_2016 7_52_49 pm](https://cloud.githubusercontent.com/assets/7307335/17795380/74560c2c-657d-11e6-909e-5666f4272e45.png)

_Also I get an error when friends sign on and off:_

**ERROR 1**

Message: ...ns\ElvUI_FriendsListColor\ElvUI_FriendsListColor.lua:29: attempt to index local 'friend' (a nil value)
Time: 08/18/16 22:14:56
Count: 2
Stack: [C]: ?
...ns\ElvUI_FriendsListColor\ElvUI_FriendsListColor.lua:29: in function <...ns\ElvUI_FriendsListColor\ElvUI_FriendsListColor.lua:24>
(tail call): ?
[C]: in function `FriendsList_Update'
Interface\FrameXML\FriendsFrame.lua:1193: in function <Interface\FrameXML\FriendsFrame.lua:1188>
(tail call): ?
[string "_:OnEvent"]:1: in function <[string "_:OnEvent"]:1>

Locals: 

**ERROR 2**

Message: ...ns\ElvUI_FriendsListColor\ElvUI_FriendsListColor.lua:29: attempt to index local 'friend' (a nil value)
Time: 08/18/16 22:16:57
Count: 1
Stack: [C]: ?
...ns\ElvUI_FriendsListColor\ElvUI_FriendsListColor.lua:29: in function <...ns\ElvUI_FriendsListColor\ElvUI_FriendsListColor.lua:24>
(tail call): ?
[C]: in function `FriendsList_Update'
Interface\FrameXML\FriendsFrame.lua:245: in function <Interface\FrameXML\FriendsFrame.lua:243>
[C]: in function`Show'
Interface\FrameXML\UIParent.lua:1580: in function `SetUIPanel'
Interface\FrameXML\UIParent.lua:1424: in function`ShowUIPanel'
Interface\FrameXML\UIParent.lua:1311: in function <Interface\FrameXML\UIParent.lua:1307>
[C]: in function `SetAttribute'
Interface\FrameXML\UIParent.lua:1974: in function`ShowUIPanel'
Interface\FrameXML\FriendsFrame.lua:1431: in function `ToggleFriendsFrame'
[string "TOGGLESOCIAL"]:1: in function <[string "TOGGLESOCIAL"]:1>

Locals:

**Comment by Bunny67** [comment]
Class text does need? After all, the name of the color of the class

**Comment by Crumdidlyumshis** [comment]
I put some spacing in-between the icon and text and changed the level to #999999 hexadecimal value.

```
local textFormat =
locale == "ruRU" and "%s%s|r, %s%d-го уровня" or
locale == "deDE" and "%s%s|r, |cffb3b3b3Stufe %s%d" or
"%s%s|r, |cff999999Level %s%d";

textFormat = " " .. classIcon .. " " .. textFormat;
```

![world of warcraft 8_19_2016 11_14_38 am](https://cloud.githubusercontent.com/assets/7307335/17816318/3c5dbbae-65fe-11e6-98d5-7aafbba0a8fb.png)

How can I add the class name after the level?

**Comment by Bunny67** [comment]
offline level text is too bright :(

**Comment by Crumdidlyumshis** [comment]
im gonna close this.
