### ISSUE TITLE
Friend Options Missing

### ISSUE THREAD

**Issue by Crumdidlyumshis** [ElvUI/ElvUI_FriendsListColor#3]
Add Friend missing
Remove Friend missing

Add Friend in /who not working.

![world of warcraft 8_19_2016 1_44_11 pm](https://cloud.githubusercontent.com/assets/7307335/17820698/b1afb9ba-6613-11e6-80d3-fa8e7bd4c9b5.png)
![world of warcraft 8_19_2016 1_44_47 pm](https://cloud.githubusercontent.com/assets/7307335/17820696/b1ad788a-6613-11e6-81f1-16cd8518b947.png)
![world of warcraft 8_19_2016 1_45_14 pm](https://cloud.githubusercontent.com/assets/7307335/17820697/b1af6b22-6613-11e6-8814-ef4791981fb7.png)

**Comment by Bunny67** [comment]
do not understand((

**Comment by Crumdidlyumshis** [comment]
Щелчок правой кнопкой мыши

Ни один вариант не добавить друга или удалить друга. Последнее обновление сломал его.

**Comment by Bunny67** [comment]
In my earlier it was not

**Comment by Crumdidlyumshis** [comment]
![world of warcraft 8_19_2016 2_01_10 pm](https://cloud.githubusercontent.com/assets/7307335/17821117/93fd51b4-6615-11e6-81ff-a9b6e0b9d106.png)
![world of warcraft 8_19_2016 2_01_29 pm](https://cloud.githubusercontent.com/assets/7307335/17821118/940d9ede-6615-11e6-8a92-25b41e424ce4.png)

**Comment by Crumdidlyumshis** [comment]
Every update you make, I install the latest and test. This is latest.
Add Friend and Remove Friend do not show up.

Google Translate:

Каждое обновление вы делаете, я установить последнюю версию и тест. Это последняя.
Добавить в друзья Удалить и друзья не отображаются.

**Comment by Bunny67** [comment]
Without the addon, okay?

**Comment by Crumdidlyumshis** [comment]
Oh, the addon is not the problem. It might be ElvUI.

Google Translate:

О, аддон не является проблемой. Это может быть ElvUI.

**Comment by Bunny67** [comment]
In Russian does not necessarily translate 
For even more unclear: D

**Comment by Crumdidlyumshis** [comment]
Okay, sorry. I am just trying to make reading easier for you! :)

**Comment by Bunny67** [comment]
Without elvui, okay?

**Comment by Crumdidlyumshis** [comment]
Oh weird. I disabled everything and it still shows. Not a problem with ElvUI or addons. :(

**Comment by Bunny67** [comment]
who and guild not remove friends

Blizzard interface code

**Comment by Crumdidlyumshis** [comment]
I think i'm crazy. I might have an addon at home that adds those.
I am at work right now. 
Ignore this problem for now until I verify.

**Comment by Crumdidlyumshis** [comment]
FOUND IT! haha im stupid.

Black List

https://wow.curseforge.com/addons/black-list-siv0968/files/19-v3-3-01/

![world of warcraft 8_19_2016 2_38_18 pm](https://cloud.githubusercontent.com/assets/7307335/17822131/e7bcd0c2-661a-11e6-9a31-6e6d5c2caf59.png)
![world of warcraft 8_19_2016 2_38_26 pm](https://cloud.githubusercontent.com/assets/7307335/17822132/e7cb69c0-661a-11e6-90e3-9955c9b5ce23.png)
![world of warcraft 8_19_2016 2_38_32 pm](https://cloud.githubusercontent.com/assets/7307335/17822133/e7cd2bf2-661a-11e6-8c39-2040e2a3b8b2.png)

**Comment by Bunny67** [comment]
:)
