### ISSUE TITLE
Various Tweak

### ISSUE THREAD

**Issue by Crumdidlyumshis** [ElvUI/ElvUI_FriendsListColor#4]
Line 20:
`local classIcon = "|TInterface\\Glues\\CharacterCreate\\UI-CharacterCreate-Classes:16:16:-1:0:64:64:%d:%d:%d:%d|t";`

Line 27:
`textFormat = " " .. classIcon .. " " .. textFormat;`

![output_vzfznf](https://cloud.githubusercontent.com/assets/7307335/17822589/9f8cafa4-661d-11e6-81a2-488476393c85.gif)

**Comment by Bunny67** [comment]
smaller size?

**Comment by Crumdidlyumshis** [comment]
Little smaller and more breathing room.

**Comment by Crumdidlyumshis** [comment]
Thank you!
