### ISSUE TITLE
Offline status text

### ISSUE THREAD

**Issue by Crumdidlyumshis** [ElvUI/ElvUI_FriendsListColor#5]
Change text "Offline" to "last seen"

`%s, |cff999999Last Seen %s|r`

Retail

![image](https://cloud.githubusercontent.com/assets/7307335/18181120/4ffd680c-704f-11e6-98d3-bfc0a1d96d5b.png)

local textFormat2 = 
locale == "ruRU" and "%s, |cff999999Не всети (%s)|r" or 
locale == "deDE" and "%s, |cff999999Offline (%s)|r" or -- need translete
"%s, |cff999999Last Seen %s|r";

**Comment by Bunny67** [comment]
check
