### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by freesay** [ElvUI/ElvUI_FriendsListColor#6]
Maybe do like this?
Or make a checkbox for disable icon?
![wowscrnshot_092116_184445](https://cloud.githubusercontent.com/assets/19500175/18750191/cc37b668-80e2-11e6-9fd3-aa786237533b.jpg)

**Comment by Bunny67** [comment]
Не понял :(

**Comment by freesay** [comment]
Я думал это разные люди разрабатывают аддоны =) 
Во френдлисте можно иконку класса подкорректировать? Ну, вот чтоб она хоть чуть покрасивей выглядела =) Ну или добавить в настройки пунктик на вкл/выкл этой иконки класса.

**Comment by Bunny67** [comment]
Изначально я ее хотел отдельно сделать, но решил все токи в текст имени засунуть. Позже мб что то придумаю, на выходных.

П.с в коммитах кроме меня же никого нет :)

**Comment by freesay** [comment]
Понял, буду иметь ввиду. Спасибо =)
